# Generated by Django 3.0.8 on 2020-08-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstudentmap',
            name='is_associate',
            field=models.BooleanField(default=False),
        ),
    ]
